"""Access Recommender Agent — generates access recommendations using AI."""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, Any

from langchain_core.prompts import ChatPromptTemplate

if TYPE_CHECKING:
    from langchain_core.language_models import BaseLanguageModel
from access_control.agents.base import AgentContext, BaseAgent
from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from access_control.config import Settings
from access_control.models.schemas import AccessRecommendation


class AccessRecommenderInput(BaseModel):
    """Input for the access recommender agent."""

    principal_id: str
    access_history: list[dict[str, Any]] = Field(default_factory=list)
    peer_access: list[dict[str, Any]] = Field(default_factory=list)
    current_roles: list[dict[str, Any]] = Field(default_factory=list)
    context: dict[str, Any] = Field(default_factory=dict)


class AccessRecommenderOutput(BaseModel):
    """Output from the access recommender agent."""

    recommendations: list[dict[str, Any]] = Field(default_factory=list)
    summary: str = ""


class AccessRecommenderAgent(
    BaseAgent[AccessRecommenderInput, AccessRecommenderOutput]
):
    """Agent that generates access recommendations.

    Uses LangChain DeepAgents to analyze access patterns, peer behavior,
    and role assignments to recommend access changes such as granting
    additional permissions, revoking unused access, or flagging for review.
    """

    def __init__(self, llm: BaseLanguageModel, settings: Settings) -> None:
        super().__init__(
            llm=llm,
            settings=settings,
            name="access_recommender",
            description="Generates AI-powered access recommendations based on usage patterns",
        )

    def _build_agent(self) -> Any:
        """Build the LangChain DeepAgents instance for access recommendations."""
        system_prompt = """You are an access recommendation engine for an access control system.
Analyze the principal's access history, peer access patterns, and current roles to recommend access changes.
Follow least-privilege principles: recommend revoking unused access, granting only necessary access,
and flagging suspicious patterns for review.
Respond with a JSON object containing: recommendations (list of {resource, action, recommendation, reason, confidence}), summary."""  # noqa: E501

        prompt = ChatPromptTemplate.from_messages(
            [
                ("system", system_prompt),
                ("human", "{input}"),
            ]
        )

        chain = prompt | self.llm
        return chain

    async def run(
        self, payload: AccessRecommenderInput, context: AgentContext | None = None
    ) -> AccessRecommenderOutput:
        """Generate access recommendations for a principal.

        Args:
            payload: The principal's access data and context.
            context: Optional execution context.

        Returns:
            The recommendations generated by the agent.
        """
        agent = self._build_agent()

        input_data = {
            "input": json.dumps(
                {
                    "principal_id": payload.principal_id,
                    "access_history": payload.access_history,
                    "peer_access": payload.peer_access,
                    "current_roles": payload.current_roles,
                    "context": payload.context,
                }
            )
        }

        response = await agent.ainvoke(input_data)

        content = response.content if hasattr(response, "content") else str(response)

        try:
            parsed = json.loads(content)
            return AccessRecommenderOutput(**parsed)
        except (json.JSONDecodeError, TypeError):
            return AccessRecommenderOutput(
                summary="Failed to generate recommendations",
            )

    async def recommend(
        self,
        principal_id: str,
        access_history: list[dict[str, Any]] | None = None,
        peer_access: list[dict[str, Any]] | None = None,
        current_roles: list[dict[str, Any]] | None = None,
    ) -> list[AccessRecommendation]:
        """Generate access recommendations for a principal.

        Args:
            principal_id: The user or agent to generate recommendations for.
            access_history: Optional access history for the principal.
            peer_access: Optional peer access data for comparison.
            current_roles: Optional current role assignments.

        Returns:
            A list of access recommendations.
        """
        payload = AccessRecommenderInput(
            principal_id=principal_id,
            access_history=access_history or [],
            peer_access=peer_access or [],
            current_roles=current_roles or [],
        )
        output = await self.run(payload)

        recommendations: list[AccessRecommendation] = []
        for rec in output.recommendations:
            try:
                recommendations.append(
                    AccessRecommendation(
                        principal_id=principal_id,
                        resource=rec.get("resource", ""),
                        action=rec.get("action", ""),
                        recommendation=rec.get("recommendation", "review"),
                        reason=rec.get("reason", ""),
                        confidence=rec.get("confidence", 0.5),
                    )
                )
            except Exception:
                continue  # noqa: B112

        return recommendations
